### ISSUE TITLE
Typos: Fix instances of words being unnecessarily combined

### ISSUE THREAD

**Issue by mikeville** [TruSat/trusat-learn#8]
When copying the TruSat white paper to the formatting in these docs, a number of words were inadvertently concatenated.

For example, at the top of the [Roadmap](https://learn.trusat.org/docs/roadmap), the characters "alimitedprototype" should instead read as "a limited prototype."

If someone could scan through and fix these instances, that would be helpful.

**Comment by hanani8** [comment]
It looks like it is fixed, now, right?
Or is there any more help needed?

**Comment by mikeville** [comment]
Yes, thank you, @hanani8. On quick scan, I'm not seeing the same typos as before so I guess this has been fixed :)
